services:
  llamafactory:
    build:
      dockerfile: ./docker/docker-cuda/Dockerfile
      context: ../..
      args:
        PIP_INDEX: https://pypi.org/simple
        EXTRAS: metrics
    container_name: llamafactory
    ports:
      - "7860:7860"
      - "8000:8000"
    volumes:
      - /home/sean/Documents/ktransformers/deepseek-ai:/app/models/deepseek-ai:ro
      - /home/sean/Documents/ktransformers/LLaMA-Factory/saves:/app/saves:ro
      - /home/sean/Documents/ktransformers/kt-sft:/kt-sft:rw
    environment:
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda-12.4/lib64:/opt/conda/lib/python3.11/site-packages:/opt/conda/lib/python3.11/site-packages/torch/lib:/opt/conda/lib/python3.11/site-packages/nvidia/cublas/lib:/opt/conda/lib/python3.11/site-packages/nvidia/cudnn/lib:/opt/conda/lib/python3.11/site-packages/nvidia/cusparse/lib
      - CUDA_HOME=/usr/local/cuda
      - CUDA_VISIBLE_DEVICES=0
    ipc: host
    tty: true
    # shm_size: "16gb"  # ipc: host is set
    stdin_open: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [ gpu ]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
